---
- hosts: all # comes from the hosts file
  become: true # become sudo
  gather_facts: false # save time and not gather info
  env:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - name: set sudo password
      set_fact:
        ansible_sudo_pass: "{{ ansible_ssh_pass }}"

    - name: copy war from Jenkins to target host
      copy:
        src: /var/lib/jenkins/workspace/Amar-Deploy-on-Container-using-Ansible/webapp/target/webapp.war
        dest: /opt/docker/amar

    - name: stop current container
      command: docker stop amar-devops-container
      ignore_errors: yes # in case container doesn't exist

    - name: remove stopped container
      command: docker rm amar-devops-container
      ignore_errors: yes # in case container doesn't exist

    - name: remove docker images 
      command: docker rmi amar-devops-image:latest
      ignore_errors: yes # in case image does not exist

    - name: create docker image using war file
      command: docker build -t amar-devops-image:latest .
      args:
        chdir: /opt/docker/amar

    - name: run container from docker image
      command: docker run -d --name amar-devops-container -p 8081:8080 amar-devops-image:latest